ifneq ($(LIBRARY),)
EXTRA_FLAGS=-fpic -fno-rtti -std=c++17
endif

LLVM_INCLUDE   := `llvm-config --cxxflags` 
#LLVM_LIB       := -L$(LLVM_BUILD_DIR)/lib -lLLVM

OBJECTS=$(SOURCES:.cpp=.o)

.PHONY: all

all: $(LIBRARY) $(EXECUTABLE)

$(LIBRARY): $(OBJECTS)
	clang++ -shared -o $@ $^ $(EXTRA_FLAGS) $(LLVM_INCLUDE)

$(EXECUTABLE): $(OBJECTS)
	clang++ $^ -o $@ $(EXTRA_FLAGS) $(LLVM_INCLUDE)

%.o: %.cpp
	clang++ -c $(EXTRA_FLAGS) $(LLVM_INCLUDE) $^ -o $@

.PHONY: test run

test: $(TEST).opt.bc 

run: $(TEST).exe
	./$(TEST).exe

$(TEST).exe: $(TEST).opt.bc
	clang $< $(TEST_LIB_FLAG) -o $@

$(TEST).opt.bc: $(TEST).bc $(LIBRARY)
	opt -load-pass-plugin ./$(LIBRARY) -passes="$(PASSNAME)" $< -o $@ 
	llvm-dis $@

$(TEST).bc: $(TEST).c
	clang -c -emit-llvm $< -o $@ -Xclang -disable-O0-optnone
	llvm-dis $@

.PHONY: clean

clean:
	rm -f $(LIBRARY) $(EXECUTABLE) $(OBJECTS) *.ll *.bc *.exe
